services:
  - type: web
    name: django-ecommerce
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mypro.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mypro.settings
