# Generated by Django 5.2.1 on 2025-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='catogery',
            name='image',
            field=models.ImageField(default='catimage/default.png', upload_to='catimage/'),
        ),
    ]
