# Generated by Django 5.2.1 on 2025-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_catogery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogery',
            name='image',
            field=models.ImageField(default='catimage/default.jpg', upload_to='catimage/'),
        ),
    ]
